net:
  webPort: 8080
  apiHost: 127.0.0.1
  apiPort: 8088

auth:
  # https://www.web2generators.com/apache-tools/htpasswd-generator
  - john:$apr1$zdjw3n47$zra4fQBwxLk.BN3TYNoON0

log:
  maxFiles: 25
  maxFileSizeInMB: 5
  retentionDays: 15

alert:
  workers: 5 # total round-robin workers for alert event processing
  eventBuffer: 10 # event capacity size for each alert worker
